# Generated by Django 2.2.8 on 2019-12-27 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0002_order_orderitems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitems',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='orderitems',
            old_name='order_id',
            new_name='order',
        ),
    ]
